package quik;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




public class Securities {

    private static final List<Security> cache = Arrays.asList(
            new Security(6,     "MSNG", "+МосЭнерго"),
            new Security(399716, "AGRO", "AGRO-гдр"),
            new Security(152876, "GTLC", "GTL ао"),
            new Security(407494, "PGIL", "PGIL-ао"),
            new Security(175924, "POLY", "Polymetal"),
            new Security(388383, "YNDX", "Yandex clA"),
            new Security(181610, "QIWI", "iQIWI"),
            new Security(181867, "AESL", "iАЭССЕЛЬао"),
            new Security(22843, "UNAC", "iАвиастКао"),
            new Security(19676, "ARMD", "iАрмада"),
            new Security(82886, "VTRS", "iВТОРРЕСао"),
            new Security(74744, "DZRD", "iДонскЗР"),
            new Security(74745, "DZRDP", "iДонскЗР п"),
            new Security(35363, "DIOD", "iЗаводДИОД"),
            new Security(17137, "ISKJ", "iИСКЧ ао"),
            new Security(152517, "LVHK", "iЛевенгук"),
            new Security(20737, "ODVA", "iМедиахолд"),
            new Security(152676, "MSST", "iМультиСис"),
            new Security(81992, "NAUK", "iНПОНаука"),
            new Security(81929, "NSVZ", "iНаукаСвяз"),
            new Security(81241, "PLSM", "iПлазмек"),
            new Security(152677, "RLMN", "iРоллман"),
            new Security(388313, "RLMNP", "iРоллман-п"),
            new Security(74540, "SEMZ", "iСЭМЗ ао"),
            new Security(83122, "SKYC", "iСкайКо-ао"),
            new Security(74584, "LIFE", "iФармсинтз"),
            new Security(83121, "PRFN", "iЧЗПСН ао"),
            new Security(81040, "UTII", "iЮтинет.Ру"),
            new Security(181310, "DALM", "iэнергомаш"),
            new Security(39,    "AVAZ", "АВТОВАЗ ао"),
            new Security(40,    "AVAZP", "АВТОВАЗ ап"),
            new Security(82616, "ALBK", "АЛОР БАНК"),
            new Security(81820, "ALRS", "АЛРОСА ао"),
            new Security(81882, "ALNU", "АЛРОСА-Нюр"),
            new Security(82460, "ABRD", "АбрауДюрсо"),
            new Security(82843, "AVAN", "Авангрд-ао"),
            new Security(17564, "AKRN", "Акрон"),
            new Security(13855, "APTK", "Аптеки36и6"),
            new Security(19915, "ARSA", "Арсагера"),
            new Security(16452, "ASSB", "АстрЭнСб"),
            new Security(20702, "AMEZ", "АшинскийМЗ"),
            new Security(29,    "AFLT", "Аэрофлот"),
            new Security(20066, "BSPB", "БСП ао"),
            new Security(15914, "MMBM", "БанкМосквы"),
            new Security(35242, "BISV", "БашИнСв ао"),
            new Security(35243, "BISVP", "БашИнСв ап"),
            new Security(81757, "BANE", "Башнефт ао"),
            new Security(81758, "BANEP", "Башнефт ап"),
            new Security(21078, "BLNG", "Белон ао"),
            new Security(81901, "BRZL", "БурЗолото"),
            new Security(17942, "VRPH", "ВЕРОФАРМ"),
            new Security(19043, "VTBR", "ВТБ ао"),
            new Security(19632, "VTGK", "ВТГК"),
            new Security(17257, "VLHZ", "ВХЗ-ао"),
            new Security(16352, "VDSB", "ВЭК 01 ао"),
            new Security(81954, "VJGZ", "Варьеган"),
            new Security(81955, "VJGZP", "Варьеган-п"),
            new Security(15965, "VSMO", "Верхнесалд"),
            new Security(17068, "VZRZ", "Возрожд-ао"),
            new Security(17067, "VZRZP", "Возрожд-п"),
            new Security(16456, "VGSB", "ВолгЭнСб"),
            new Security(16457, "VGSBP", "ВолгЭнСб-п"),
            new Security(16546, "VRSB", "ВоронЭнСб"),
            new Security(16547, "VRSBP", "ВоронЭнСбп"),
            new Security(20958, "VRAO", "ВостРАО ао"),
            new Security(20959, "VRAOP", "ВостРАО ап"),
            new Security(83251, "VSYD", "ВыбСудЗ ао"),
            new Security(83252, "VSYDP", "ВыбСудЗ ап"),
            new Security(81997, "GAZA", "ГАЗ ао"),
            new Security(81998, "GAZAP", "ГАЗ ап"),
            new Security(82115, "GAZT", "ГАЗ-Тек ао"),
            new Security(81399, "GAZS", "ГАЗ-сервис"),
            new Security(81398, "GAZC", "ГАЗКОН-ао"),
            new Security(16842, "GAZP", "ГАЗПРОМ ао"),
            new Security(795,   "GMKN", "ГМКНорНик"),
            new Security(509,   "GUMM", "ГУМ"),
            new Security(152397, "RTGZ", "ГазпРнД ао"),
            new Security(2,     "SIBN", "Газпрнефть"),
            new Security(17698, "HALS", "Галс-Девел"),
            new Security(175842, "GTPR", "ГлТоргПрод"),
            new Security(20708, "FESH", "ДВМП ао"),
            new Security(18564, "DIXY", "ДИКСИ ао"),
            new Security(19724, "DVEC", "ДЭК ао"),
            new Security(16825, "DASB", "ДагСб ао"),
            new Security(175840, "BGDE", "Деликатесы"),
            new Security(17919, "DGBZ", "Дорогбж ао"),
            new Security(17920, "DGBZP", "Дорогбж ап"),
            new Security(181674, "ZHIV", "Живой Оф"),
            new Security(82001, "ZVEZ", "ЗВЕЗДА ао"),
            new Security(81918, "ZILL", "ЗИЛ ао"),
            new Security(556,   "ZMZN", "ЗМЗ-ао"),
            new Security(603,   "ZMZNP", "ЗМЗ-ап"),
            new Security(388276, "IDJT", "ИДЖАТ"),
            new Security(81786, "RUSI", "ИКРУСС-ИНВ"),
            new Security(15547, "IRKT", "ИРКУТ-3"),
            new Security(81887, "IGSTP", "Ижсталь ап"),
            new Security(81885, "IGST", "Ижсталь2ао"),
            new Security(81886, "IGST03", "Ижсталь3ао"),
            new Security(20516, "IRAO", "ИнтерРАОао"),
            new Security(9,     "IRGZ", "ИркЭнерго"),
            new Security(15544, "KMAZ", "КАМАЗ"),
            new Security(17359, "KZMS", "КЗМС ао"),
            new Security(22525, "KMEZ", "КМЗ"),
            new Security(16284, "KTSB", "КСБ ао"),
            new Security(16285, "KTSBP", "КСБ ап"),
            new Security(81943, "KUNF", "КУЗОЦМ ао"),
            new Security(16329, "KLSB", "КалужскСК"),
            new Security(20030, "KCHE", "КамчатЭ ао"),
            new Security(20498, "KCHEP", "КамчатЭ ап"),
            new Security(18310, "TGKD", "Квадра"),
            new Security(18391, "TGKDP", "Квадра-п"),
            new Security(75094, "KSGR", "Кокс ао"),
            new Security(20710, "KOGK", "КоршГОК ао"),
            new Security(81903, "KMTZ", "КосогМЗ ао"),
            new Security(511,   "KROTP", "КрасОкт-1п"),
            new Security(510,   "KROT", "КрасОкт-ао"),
            new Security(15518, "KRSG", "КраснГЭС"),
            new Security(20912, "KRSB", "Красэсб ао"),
            new Security(20913, "KRSBP", "Красэсб ап"),
            new Security(66692, "KUSTP", "КубанСт ап"),
            new Security(19916, "KBSB", "КубаньЭнСб"),
            new Security(522,   "KUBE", "Кубанэнр"),
            new Security(35285, "KBTK", "КузбТК ао"),
            new Security(20204, "KZBE", "Кузбасэнрг"),
            new Security(83165, "KUZB", "КузнецкийБ"),
            new Security(81941, "KAZT", "Куйбазот"),
            new Security(81942, "KAZTP", "Куйбазот-п"),
            new Security(83261, "KGKC", "КурганГКао"),
            new Security(152350, "KGKCP", "КурганГКап"),
            new Security(19736, "LSRG", "ЛСР ао"),
            new Security(8,     "LKOH", "ЛУКОЙЛ"),
            new Security(16276, "LPSB", "ЛЭСК ао"),
            new Security(22094, "LNZLP", "Лензол. ап"),
            new Security(21004, "LNZL", "Лензолото"),
            new Security(385792, "LNTA", "Лента др"),
            new Security(542,   "LSNGP", "Ленэнерг-п"),
            new Security(31,    "LSNG", "Ленэнерго"),
            new Security(19737, "MVID", "М.видео"),
            new Security(12983, "MGTSP", "МГТС-4ап"),
            new Security(12984, "MGTS", "МГТС-5ао"),
            new Security(20947, "MERF", "МЕРИДИАН"),
            new Security(16782, "MAGN", "ММК"),
            new Security(80390, "MNFD", "МН-фонд ао"),
            new Security(16917, "MSRS", "МОЭСК"),
            new Security(20309, "MRKZ", "МРСК СЗ"),
            new Security(20412, "MRKK", "МРСК СК"),
            new Security(20402, "MRKU", "МРСК Ур"),
            new Security(20107, "MRKP", "МРСК ЦП"),
            new Security(20235, "MRKC", "МРСК Центр"),
            new Security(20286, "MRKV", "МРСКВол"),
            new Security(20346, "MRKS", "МРСКСиб"),
            new Security(20681, "MRKY", "МРСКЮга ао"),
            new Security(15523, "MTSS", "МТС-ао"),
            new Security(74562, "MAGE", "МагадЭн ао"),
            new Security(74563, "MAGEP", "МагадЭн ап"),
            new Security(17086, "MGNT", "Магнит ао"),
            new Security(16330, "MISB", "МариЭнСб"),
            new Security(16331, "MISBP", "МариЭнСб-п"),
            new Security(81907, "MASZ", "МашЗавод"),
            new Security(152516, "MFON", "МегаФон ао"),
            new Security(30,    "MFGS", "Мегион-ао"),
            new Security(51,    "MFGSP", "Мегион-ап"),
            new Security(81829, "MGVM", "МедиаВиМ"),
            new Security(21018, "MTLR", "Мечел ао"),
            new Security(80745, "MTLRP", "Мечел ап"),
            new Security(16359, "MRSB", "МордЭнСб"),
            new Security(81944, "MORI", "Морион ао"),
            new Security(152798, "MOEX", "МосБиржа"),
            new Security(82890, "MOBB", "МосОблБанк"),
            new Security(16933, "MSSB", "МосЭС ао"),
            new Security(74549, "MSTT", "Мостотрест"),
            new Security(21116, "MOTZ", "Мотовил ао"),
            new Security(81945, "MUGS", "МурмТЭЦ-ао"),
            new Security(81946, "MUGSP", "МурмТЭЦ-п"),
            new Security(20100, "NKNC", "НКНХ ао"),
            new Security(20101, "NKNCP", "НКНХ ап"),
            new Security(17046, "NLMK", "НЛМК ао"),
            new Security(19629, "NMTP", "НМТП ао"),
            new Security(81287, "NFAZ", "Нефтекамск"),
            new Security(16615, "NNSB", "НижгорСб"),
            new Security(16616, "NNSBP", "НижгорСб-п"),
            new Security(81947, "NKSH", "Нижкамшина"),
            new Security(17370, "NVTK", "Новатэк ао"),
            new Security(66694, "SXPNP", "Новопл ап"),
            new Security(20893, "NVNG", "Новсибэн"),
            new Security(81948, "NVNGP", "Новсибэн-п"),
            new Security(18684, "OGKB", "ОГК-2 ао"),
            new Security(175781, "UCSS", "ОКС ао"),
            new Security(15844, "OMZZP", "ОМЗ-ап"),
            new Security(21006, "OSMP", "ОМПК ао"),
            new Security(20711, "OPIN", "ОПИН ао"),
            new Security(22891, "OMSH", "Омскшина"),
            new Security(81856, "KZOS", "ОргСинт ао"),
            new Security(81857, "KZOSP", "ОргСинт ап"),
            new Security(407627, "OTCP", "Отисифарм"),
            new Security(80728, "OFCB", "ОткрФКБ ао"),
            new Security(18654, "PIKK", "ПИК ао"),
            new Security(17850, "PRIM", "ПМП ао"),
            new Security(35247, "PRTK", "ПРОТЕК ао"),
            new Security(81896, "PAZA", "ПавлАвт ао"),
            new Security(16909, "PMSBP", "ПермьЭнС-п"),
            new Security(16908, "PMSB", "ПермьЭнСб"),
            new Security(81908, "PETR", "Петр ао"),
            new Security(17123, "PLZL", "ПолюсЗолот"),
            new Security(80818, "PRMB", "Приморье"),
            new Security(22806, "PRIN", "ПроектИ ао"),
            new Security(152320, "PSBR", "Промсвб ао"),
            new Security(74779, "RBCM", "РБК ао"),
            new Security(181934, "RGSS", "РГС ао"),
            new Security(181755, "RDRB", "РДБанк ао"),
            new Security(66644, "RNAV", "РНТ"),
            new Security(20637, "ROST", "РОСИНТЕРао"),
            new Security(16610, "GRAZ", "Разгуляй"),
            new Security(17713, "RASP", "Распадская"),
            new Security(35248, "REBR", "РегБР ао"),
            new Security(66693, "RODNP", "Родина ап"),
            new Security(16866, "ROSB", "Росбанк ао"),
            new Security(17273, "ROSN", "Роснефть"),
            new Security(20971, "RSTI", "Россети ао"),
            new Security(20972, "RSTIP", "Россети ап"),
            new Security(7,     "RTKM", "Ростел -ао"),
            new Security(15,    "RTKMP", "Ростел -ап"),
            new Security(16783, "RTSB", "РостовЭС"),
            new Security(16784, "RTSBP", "РостовЭС-п"),
            new Security(20266, "HYDR", "РусГидро"),
            new Security(74718, "RUALR", "Русал рдр"),
            new Security(66893, "RUGR", "Русгрэйн"),
            new Security(181316, "ROLO", "Русолово"),
            new Security(20712, "RUSP", "Русполимет"),
            new Security(35238, "RSEA", "РуссМоре"),
            new Security(16455, "RZSB", "РязЭнСб"),
            new Security(22401, "SZPR", "СЗПароход"),
            new Security(20892, "MGNZ", "СМЗ-ао"),
            new Security(16080, "SVAV", "СОЛЛЕРС"),
            new Security(445,   "SAGO", "СамарЭн-ао"),
            new Security(70,    "SAGOP", "СамарЭн-ап"),
            new Security(81891, "KRKN", "СаратНПЗ"),
            new Security(81892, "KRKNP", "СаратНПЗ-п"),
            new Security(11,    "SARE", "СаратЭн-ао"),
            new Security(24,    "SAREP", "СаратЭн-ап"),
            new Security(3,     "SBER", "Сбербанк"),
            new Security(23,    "SBERP", "Сбербанк-п"),
            new Security(16136, "CHMF", "СевСт-ао"),
            new Security(21166, "SELL", "Селестра"),
            new Security(81360, "SELG", "Селигдар"),
            new Security(82610, "SELGP", "Селигдар-п"),
            new Security(19651, "SYNG", "Синерг. ао"),
            new Security(19715, "AFKS", "Система ао"),
            new Security(15723, "JNOSP", "Слав-ЯНОСп"),
            new Security(15722, "JNOS", "Славн-ЯНОС"),
            new Security(20087, "STSB", "СтаврЭнСб"),
            new Security(20088, "STSBP", "СтаврЭнСбп"),
            new Security(4,     "SNGS", "Сургнфгз"),
            new Security(13,    "SNGSP", "Сургнфгз-п"),
            new Security(81914, "TANL", "ТАНТАЛ ао"),
            new Security(81915, "TANLP", "ТАНТАЛ ап"),
            new Security(18382, "TGKA", "ТГК-1"),
            new Security(18176, "TGKN", "ТГК-14"),
            new Security(17597, "TGKB", "ТГК-2"),
            new Security(18189, "TGKBP", "ТГК-2 ап"),
            new Security(20716, "TUZA", "ТЗА ао"),
            new Security(81899, "TGKO", "ТКЗ ао"),
            new Security(81905, "KRKO", "ТКЗКК ао"),
            new Security(81906, "KRKOP", "ТКЗКК ап"),
            new Security(74746, "TUCH", "ТКСМ ао"),
            new Security(18441, "TRMK", "ТМК ао"),
            new Security(80593, "TAER", "ТРАНСАЭРао"),
            new Security(386343, "NBTR", "ТРАСТ ао"),
            new Security(383537, "TFKF-001D", "ТФК-Ф ао01"),
            new Security(388314, "TFKF", "ТФК-Финанс"),
            new Security(19012, "TAVR", "Таврическ."),
            new Security(16265, "TASB", "ТамбЭнСб"),
            new Security(16266, "TASBP", "ТамбЭнСб-п"),
            new Security(825,   "TATN", "Татнфт 3ао"),
            new Security(826,   "TATNP", "Татнфт 3ап"),
            new Security(18371, "TTLK", "Таттел. ао"),
            new Security(21002, "CNTL", "Телеграф"),
            new Security(81575, "CNTLP", "Телеграф-п"),
            new Security(16797, "TORS", "ТомскРП ао"),
            new Security(16798, "TORSP", "ТомскРП ап"),
            new Security(74561, "TRCN", "ТрансК ао"),
            new Security(1012,  "TRNFP", "Транснф ап"),
            new Security(82165, "TRUDP", "Труд ап"),
            new Security(16805, "UAZA", "УАЗ ао"),
            new Security(75124, "URFD", "УКОРФ ао"),
            new Security(81930, "UFMO", "УМПО ао"),
            new Security(82611, "URKZ", "УрКузница"),
            new Security(81953, "USBN", "УралСиб ао"),
            new Security(19623, "URKA", "Уркалий-ао"),
            new Security(20509, "FEES", "ФСК ЕЭС ао"),
            new Security(19717, "PHST", "Фармстанд"),
            new Security(81858, "NPOF", "Физика ао"),
            new Security(82164, "FORTP", "Форт ап"),
            new Security(81114, "PHOR", "ФосАгро ао"),
            new Security(81939, "HIMC", "Химпром ао"),
            new Security(81940, "HIMCP", "Химпром ап"),
            new Security(19095, "WTCM", "ЦМТ ао"),
            new Security(19096, "WTCMP", "ЦМТ ап"),
            new Security(21000, "CHKZ", "ЧКПЗ ао"),
            new Security(21001, "CHMK", "ЧМК ао"),
            new Security(20999, "CHEP", "ЧТПЗ ао"),
            new Security(19960, "CHZN", "ЧЦЗ ао"),
            new Security(16712, "CLSB", "ЧелябЭС ао"),
            new Security(16713, "CLSBP", "ЧелябЭС ап"),
            new Security(20125, "GCHE", "ЧеркизГ-ао"),
            new Security(81933, "CHGZ", "ЧерногНефт"),
            new Security(18584, "EONR", "Э.ОНРоссия"),
            new Security(81935, "ERCO", "ЭРКО ао"),
            new Security(81934, "ELTZ", "Электрцинк"),
            new Security(16440, "ENRU", "ЭнелРос ао"),
            new Security(20321, "RKKE", "ЭнергияРКК"),
            new Security(15522, "UTAR", "ЮТэйр ао"),
            new Security(82493, "UNKL", "ЮУНК ао"),
            new Security(20717, "UKUZ", "ЮжКузб. ао"),
            new Security(15736, "YRSL", "ЯРОСЛАВИЧ"),
            new Security(81917, "YAKG", "ЯТЭК ао"),
            new Security(81769, "YKENP", "Якутскэн-п"),
            new Security(81766, "YKEN", "Якутскэнрг"),
            new Security(80316, "YASH", "ЯрШинЗ ао"),
            new Security(16342, "YRSB", "ЯрослСК"),
            new Security(16343, "YRSBP", "ЯрослСК-п")
    );


    private static final Map<String, Security> getByCode;


    static {
        Map<String, Security> temp = new HashMap<String, Security>();

        for (Security item : cache)
            temp.put(item.getCode(), item);

        getByCode = Collections.unmodifiableMap(temp);
    }


    public static Security getByCode(String code) {
        return getByCode.get(code);
    }


    public static Map<String, Security> getByCode() {
        return getByCode;
    }

}
